#!/bin/bash
# run-server --- Run app in a web server (port 8080 default).
set -e

cd $PROJ_DIR

if [[ "$1" == "--build" ]]; then
    PORT=8081
    cd build
else
    PORT=8080
fi

echo "Serving $(pwd) on port $PORT."

python -m webbrowser -t http://localhost:$PORT
python -m SimpleHTTPServer $PORT
